# Generated by Django 3.2.6 on 2023-10-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_number', models.CharField(max_length=40, verbose_name='کد سفارش')),
                ('tracking_number', models.CharField(max_length=300, verbose_name='کد رهگیری')),
                ('customer', models.CharField(max_length=300, verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'کد رهگیری',
                'verbose_name_plural': 'کد های رهگیری',
            },
        ),
        migrations.CreateModel(
            name='RequestCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_number', models.CharField(max_length=40, verbose_name='کد سفارش')),
                ('customer', models.CharField(max_length=300, verbose_name='مشتری')),
                ('status', models.CharField(max_length=300, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'مشتری درخواست دهنده',
                'verbose_name_plural': 'مشتری های درخواست دهنده',
            },
        ),
    ]
