# Generated by Django 3.2.6 on 2023-10-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercodes',
            name='customer',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='ordercodes',
            name='orders_number',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='کد سفارش'),
        ),
        migrations.AlterField(
            model_name='ordercodes',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='کد رهگیری'),
        ),
        migrations.AlterField(
            model_name='requestcustomer',
            name='customer',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='requestcustomer',
            name='orders_number',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='کد سفارش'),
        ),
        migrations.AlterField(
            model_name='requestcustomer',
            name='status',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='وضعیت'),
        ),
    ]
