# Generated by Django 3.2.6 on 2024-03-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_ordercodes_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercodes',
            name='orders_number',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='کد سفارش'),
        ),
    ]
