# Generated by Django 3.2.6 on 2024-03-06 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_ordercodes_orders_number'),
    ]

    operations = [
    ]
